# Copyright 2021-2022 Telematics Technologies sp. z o.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if not .Values.rabbitmq.definitions }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-default-user-credentials
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: {{ .Release.Name }}-default-user
spec:
  tags:
    - administrator
  rabbitmqClusterReference:
    name: {{ .Release.Name }}
  importCredentialsSecret:
    name: {{ .Release.Name }}-default-user-credentials
{{- end }}
